personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: false

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: 'John'
  lastName: 'Doe'
  # Date of birth (MM/DD/YYYY)
  dob: '01/01/2001'
  # Use real email to get appointment infomation
  email: ''
  # Not really needed but good to have a real one
  lastFourSSN: '1001'
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: ''

  # If you are doing new Texas DL appointment, you can leave this blank
  # Put your real Texas DL number here, if you are doing DL renewal appointments.
  # WARNING: Use number only (Ex: 111111111)
  cardNumber: ''

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Search DPS Locations by City Name, if City name is given, zipCode is ignored.
  # If you don't want to search by city name, set it to ['']
  cityName: ['']
  # Zipcode of your location. Can add more DPS location by using ',' for multiple zipcode
  zipCode: ['75067', '75080']
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: false
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 15
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: ['Monday']
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: false
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    ## Start date: start and end will start counting from this date
    # MM/DD/YYYY format, if blank will use current date
    # If the date input is invalid or in the past, the app will automatically use the current date as start date
    startDate: null
    start: 0
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 6
    end: 18

appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: false
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 50000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3
  # Read this for more infomation: https://github.com/phamleduy04/texas-dps-scheduler/wiki/Captcha-(Auth-Token)
  captcha:
    # Avaliable options: solver, browser or manual
    strategy: 'browser'
    solverOptions:
      solverService: 'capsolver'
      solverApiToken: ''
  # ntfy.sh push notification
  pushNotifcation:
    enabled: false
    baseURL: ''
    topicName: ''
    token: ''
